---
broker:
  username: admin
  password: pass
  nats: 'nats//user:pass@ip:4222'
  # database_url ?

redislabs:
  auth:
    username: admin
    password: pass
  nodes:
    - 10.10.1.1
    - 10.10.1.2



